spring.application.name=event-booking-api

spring.datasource.url=jdbc:mysql://localhost:3306/event_booking?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Nampro1595@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.time-zone=Asia/Ho_Chi_Minh

server.port=8080

# Database Initialization
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# JWT Configuration
app.jwt.secret=YourSuperSecretKeyForJWTTokenGenerationMustBeAtLeast256BitsLong2024EventBooking
app.jwt.expiration=86400000

# File upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Email Configuration (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hoangnguyen6533@gmail.com
spring.mail.password=pkvl cuai kcnz hgkv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# VNPay Sandbox Configuration
vnpay.tmn-code=VELS5U0P
vnpay.hash-secret=U27A71PZD9L43SB5EJI5ODZRKHLNS4BH
vnpay.url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.return-url=http://localhost:5173/payment-result
